services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: __PROJECT_NAME__
        env_file:
            - api.env
        depends_on:
            db:
                condition: service_healthy
        networks:
            - __PROJECT_NAME__
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        restart: always
