services:
    db:
        container_name: db
        image: postgres
        ports:
            - '5432:5432'
        env_file:
            - db.env
        volumes:
            - __PROJECT_NAME__-db:/var/lib/postgresql/data
        networks:
            - __PROJECT_NAME__
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d __DB_NAME__']
            interval: 5s
            timeout: 2s
            retries: 10
