services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - '3100:3000'
        restart: always
        volumes:
            - __PROJECT_NAME__-grafana:/var/lib/grafana
        networks:
            - __PROJECT_NAME__
